.\" -*- nroff -*-
.TH JETRING-ACCEPT 1 "" "" "jetring commands"
.SH NAME
jetring-accept \- accept a changeset
.SH SYNOPSIS
.B jetring-accept dir changeset
.SH DESCRIPTION
Accepts a changeset and adds it to the jetring directory "dir", updating
the dir/index file, and optionally gpg signing it.
.SH AUTHOR 
Joey Hess, <joey@kitenet.net>.
.SH "SEE ALSO"
.BR jetring (7)
